-- Baseline: the schema exactly as Hibernate had built it at the point
-- Flyway took over. Dumped from the live database rather than written
-- by hand, so it cannot disagree with what the entities expect.
--
-- Every change after this one is its own numbered file. Nothing edits
-- this file again.

CREATE TABLE public.agents (
    id bigint NOT NULL,
    active boolean NOT NULL,
    code character varying(255) NOT NULL,
    commission_paid numeric(12,2) NOT NULL,
    commission_percent integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    location character varying(255),
    phone_number character varying(255) NOT NULL
);

ALTER TABLE public.agents ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.agents_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.audit_events (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    actor character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    detail character varying(500) NOT NULL
);

ALTER TABLE public.audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.branches (
    id bigint NOT NULL,
    active boolean NOT NULL,
    contact_phone character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    name character varying(255) NOT NULL,
    town character varying(255)
);

ALTER TABLE public.branches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.branches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.c2b_payments (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    bill_ref_number character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    months_credited integer,
    note character varying(300),
    payer_name character varying(255),
    phone_number character varying(255),
    status character varying(255) NOT NULL,
    subscriber_id bigint,
    transaction_id character varying(255) NOT NULL,
    CONSTRAINT c2b_payments_status_check CHECK (((status)::text = ANY ((ARRAY['MATCHED'::character varying, 'UNMATCHED'::character varying, 'APPLIED_MANUALLY'::character varying])::text[])))
);

ALTER TABLE public.c2b_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.c2b_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.custom_plan_settings (
    id bigint NOT NULL,
    bandwidth character varying(255),
    enabled boolean NOT NULL,
    max_minutes integer NOT NULL,
    min_minutes integer NOT NULL,
    price_per_hour numeric(10,2) NOT NULL
);

CREATE TABLE public.direct_messages (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    body character varying(2000),
    created_at timestamp(6) with time zone NOT NULL,
    from_admin boolean NOT NULL,
    photo_filename character varying(255),
    read_by_recipient boolean NOT NULL,
    technician character varying(255) NOT NULL
);

ALTER TABLE public.direct_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.direct_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.equipment (
    id bigint NOT NULL,
    branch_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    kind character varying(255) NOT NULL,
    mac_address character varying(255),
    model character varying(255),
    name character varying(255) NOT NULL,
    notes character varying(1000),
    purchase_cost numeric(38,2),
    purchased_at date,
    quantity integer,
    serial_number character varying(255),
    status character varying(255) NOT NULL,
    subscriber_id bigint,
    technician_id bigint,
    updated_at timestamp(6) with time zone,
    warranty_months integer,
    CONSTRAINT equipment_kind_check CHECK (((kind)::text = ANY ((ARRAY['ROUTER'::character varying, 'ONT'::character varying, 'ACCESS_POINT'::character varying, 'SWITCH'::character varying, 'CABLE'::character varying, 'ANTENNA'::character varying, 'POWER'::character varying, 'TOOL'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT equipment_status_check CHECK (((status)::text = ANY ((ARRAY['IN_STOCK'::character varying, 'WITH_TECHNICIAN'::character varying, 'DEPLOYED'::character varying, 'FAULTY'::character varying, 'RETIRED'::character varying])::text[])))
);

ALTER TABLE public.equipment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.equipment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.expenses (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    category character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(255) NOT NULL,
    incurred_on date NOT NULL,
    recorded_by character varying(255),
    CONSTRAINT expenses_category_check CHECK (((category)::text = ANY ((ARRAY['BANDWIDTH'::character varying, 'EQUIPMENT'::character varying, 'RENT'::character varying, 'SALARIES'::character varying, 'TRANSPORT'::character varying, 'POWER'::character varying, 'LICENCES'::character varying, 'MARKETING'::character varying, 'OTHER'::character varying])::text[])))
);

ALTER TABLE public.expenses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.expenses_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.fiber_nodes (
    id bigint NOT NULL,
    address character varying(255),
    capacity integer,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    kind character varying(255) NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    name character varying(255) NOT NULL,
    notes character varying(1000),
    parent_id bigint,
    router_id bigint,
    status character varying(255) NOT NULL,
    subscriber_id bigint,
    updated_at timestamp(6) with time zone,
    used integer,
    CONSTRAINT fiber_nodes_kind_check CHECK (((kind)::text = ANY ((ARRAY['POP'::character varying, 'OLT'::character varying, 'CLOSURE'::character varying, 'SPLITTER'::character varying, 'ODB'::character varying, 'DROP'::character varying])::text[]))),
    CONSTRAINT fiber_nodes_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'ACTIVE'::character varying, 'FAULT'::character varying, 'DECOMMISSIONED'::character varying])::text[])))
);

ALTER TABLE public.fiber_nodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fiber_nodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.fiber_routes (
    id bigint NOT NULL,
    cores integer,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    from_node_id bigint NOT NULL,
    kind character varying(255) NOT NULL,
    length_meters integer,
    name character varying(255),
    notes character varying(1000),
    status character varying(255) NOT NULL,
    to_node_id bigint NOT NULL,
    updated_at timestamp(6) with time zone,
    waypoints character varying(4000),
    CONSTRAINT fiber_routes_kind_check CHECK (((kind)::text = ANY ((ARRAY['BACKBONE'::character varying, 'DISTRIBUTION'::character varying, 'DROP'::character varying])::text[]))),
    CONSTRAINT fiber_routes_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'ACTIVE'::character varying, 'FAULT'::character varying, 'DECOMMISSIONED'::character varying])::text[])))
);

ALTER TABLE public.fiber_routes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fiber_routes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.invoices (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    due_on date NOT NULL,
    issued_on date NOT NULL,
    months integer NOT NULL,
    number character varying(255) NOT NULL,
    paid_at timestamp(6) with time zone,
    payment_reference character varying(255),
    status character varying(255) NOT NULL,
    subscriber_id bigint NOT NULL,
    net_amount numeric(38,2),
    vat_amount numeric(38,2),
    vat_inclusive boolean,
    vat_rate numeric(38,2),
    CONSTRAINT invoices_status_check CHECK (((status)::text = ANY ((ARRAY['UNPAID'::character varying, 'PAID'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.leads (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    full_name character varying(255) NOT NULL,
    interested_in character varying(255),
    location character varying(255),
    notes character varying(1000),
    phone_number character varying(255) NOT NULL,
    quoted_fee numeric(38,2),
    source character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    subscriber_id bigint,
    updated_at timestamp(6) with time zone,
    CONSTRAINT leads_source_check CHECK (((source)::text = ANY ((ARRAY['WALK_IN'::character varying, 'REFERRAL'::character varying, 'ONLINE'::character varying, 'PHONE_CALL'::character varying, 'FIELD_VISIT'::character varying, 'OTHER'::character varying])::text[]))),
    CONSTRAINT leads_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'CONTACTED'::character varying, 'QUOTED'::character varying, 'CONVERTED'::character varying, 'LOST'::character varying])::text[])))
);

ALTER TABLE public.leads ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.leads_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ledger_adjustments (
    id bigint NOT NULL,
    amount numeric(12,2) NOT NULL,
    applied_on date NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    kind character varying(255) NOT NULL,
    reason character varying(255) NOT NULL,
    subscriber_id bigint NOT NULL,
    CONSTRAINT ledger_adjustments_kind_check CHECK (((kind)::text = ANY ((ARRAY['CREDIT_NOTE'::character varying, 'DISCOUNT'::character varying, 'WRITE_OFF'::character varying, 'PENALTY'::character varying])::text[])))
);

ALTER TABLE public.ledger_adjustments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ledger_adjustments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.maintenance_events (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    description character varying(2000),
    estimated_downtime_minutes integer,
    scheduled_end timestamp(6) with time zone NOT NULL,
    scheduled_start timestamp(6) with time zone NOT NULL,
    status character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    CONSTRAINT maintenance_events_status_check CHECK (((status)::text = ANY ((ARRAY['PLANNED'::character varying, 'COMPLETED'::character varying])::text[])))
);

ALTER TABLE public.maintenance_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maintenance_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.messaging_settings (
    id bigint NOT NULL,
    alert_phone character varying(255),
    sms_api_key character varying(255),
    sms_enabled boolean NOT NULL,
    sms_sender_id character varying(255),
    sms_username character varying(255),
    updated_at timestamp(6) with time zone,
    updated_by character varying(255),
    whatsapp_access_token character varying(1000),
    whatsapp_enabled boolean NOT NULL,
    whatsapp_phone_number_id character varying(255)
);

CREATE TABLE public.mikrotik_settings (
    id bigint NOT NULL,
    certificate character varying(255),
    dns_name character varying(255),
    enabled boolean NOT NULL,
    host character varying(255),
    hotspot_server character varying(255),
    interface_name character varying(255),
    password character varying(255),
    port integer NOT NULL,
    use_ssl boolean NOT NULL,
    username character varying(255),
    mac_binding boolean
);

CREATE TABLE public.notification_templates (
    template_key character varying(255) NOT NULL,
    body character varying(640) NOT NULL,
    enabled boolean NOT NULL,
    updated_at timestamp(6) with time zone,
    CONSTRAINT notification_templates_template_key_check CHECK (((template_key)::text = ANY ((ARRAY['VOUCHER_ISSUED'::character varying, 'TRIAL_ISSUED'::character varying, 'SUBSCRIPTION_PAID'::character varying, 'EXPIRY_REMINDER'::character varying, 'SUBSCRIPTION_SUSPENDED'::character varying, 'SUBSCRIPTION_EXTENDED'::character varying])::text[])))
);

CREATE TABLE public.outbound_messages (
    id bigint NOT NULL,
    body character varying(2000) NOT NULL,
    campaign_ref character varying(255),
    channel character varying(255) NOT NULL,
    cost numeric(38,2),
    created_at timestamp(6) with time zone NOT NULL,
    error character varying(500),
    recipient character varying(255) NOT NULL,
    recipient_name character varying(255),
    sent_by character varying(255),
    status character varying(255) NOT NULL,
    CONSTRAINT outbound_messages_channel_check CHECK (((channel)::text = ANY ((ARRAY['WHATSAPP'::character varying, 'SMS'::character varying])::text[]))),
    CONSTRAINT outbound_messages_status_check CHECK (((status)::text = ANY ((ARRAY['SENT'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.outbound_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.outbound_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payment_gateways (
    id bigint NOT NULL,
    account_name character varying(255),
    account_number character varying(255),
    active boolean NOT NULL,
    bank_name character varying(255),
    consumer_key character varying(255),
    consumer_secret character varying(255),
    environment character varying(255),
    instructions character varying(1000),
    kind character varying(255) NOT NULL,
    passkey character varying(255),
    paybill_number character varying(255),
    short_code character varying(255),
    till_number character varying(255),
    updated_at timestamp(6) with time zone,
    updated_by character varying(255),
    CONSTRAINT payment_gateways_environment_check CHECK (((environment)::text = ANY ((ARRAY['SANDBOX'::character varying, 'PRODUCTION'::character varying])::text[]))),
    CONSTRAINT payment_gateways_kind_check CHECK (((kind)::text = ANY ((ARRAY['MPESA_API'::character varying, 'MPESA_PAYBILL_MANUAL'::character varying, 'MPESA_TILL_MANUAL'::character varying, 'BANK_TRANSFER'::character varying])::text[])))
);

ALTER TABLE public.payment_gateways ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_gateways_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payments (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    checkout_request_id character varying(255),
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    mpesa_receipt_number character varying(255),
    phone_number character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    plan_id bigint NOT NULL,
    voucher_id bigint,
    custom_minutes integer,
    CONSTRAINT payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.payout_requests (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    note character varying(500),
    status character varying(255) NOT NULL,
    technician character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    CONSTRAINT payout_requests_status_check CHECK (((status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'PAID'::character varying, 'REJECTED'::character varying])::text[])))
);

ALTER TABLE public.payout_requests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payout_requests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.plan_routers (
    plan_id bigint NOT NULL,
    router_id bigint
);

CREATE TABLE public.plans (
    id bigint NOT NULL,
    active boolean NOT NULL,
    bandwidth character varying(255),
    data_limit_mb integer,
    duration_minutes integer NOT NULL,
    mikrotik_profile character varying(255),
    name character varying(255) NOT NULL,
    price numeric(10,2) NOT NULL,
    max_devices integer,
    availability character varying(255),
    burst_limit character varying(255),
    burst_threshold character varying(255),
    burst_time character varying(255),
    fup_action character varying(255),
    fup_enabled boolean,
    fup_limit_mb integer,
    fup_rate character varying(255),
    schedule_enabled boolean,
    schedule_from time(0) without time zone,
    schedule_to time(0) without time zone,
    type character varying(255),
    CONSTRAINT plans_availability_check CHECK (((availability)::text = ANY ((ARRAY['LIVE'::character varying, 'HIDDEN'::character varying, 'OFF'::character varying])::text[]))),
    CONSTRAINT plans_fup_action_check CHECK (((fup_action)::text = ANY ((ARRAY['THROTTLE'::character varying, 'BLOCK'::character varying, 'NOTIFY'::character varying])::text[]))),
    CONSTRAINT plans_type_check CHECK (((type)::text = ANY ((ARRAY['HOTSPOT'::character varying, 'PPPOE'::character varying])::text[])))
);

ALTER TABLE public.plans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.plans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.portal_settings (
    id bigint NOT NULL,
    accent_color character varying(255),
    background_color character varying(255),
    business_name character varying(255) NOT NULL,
    headline character varying(255),
    logo_filename character varying(255),
    subheadline character varying(255),
    support_phone character varying(255),
    terms_text character varying(4000),
    trial_enabled boolean NOT NULL,
    trial_minutes integer NOT NULL
);

CREATE TABLE public.promotions (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    discount_percent integer NOT NULL,
    ends_at timestamp(6) with time zone NOT NULL,
    starts_at timestamp(6) with time zone NOT NULL,
    title character varying(255) NOT NULL
);

ALTER TABLE public.promotions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.promotions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.routers (
    id bigint NOT NULL,
    active_hotspot_users integer,
    active_pppoe_users integer,
    board_name character varying(255),
    branch_id bigint,
    created_at timestamp(6) with time zone NOT NULL,
    default_router boolean NOT NULL,
    enabled boolean NOT NULL,
    host character varying(255) NOT NULL,
    last_checked_at timestamp(6) with time zone,
    last_error character varying(255),
    last_seen_at timestamp(6) with time zone,
    location character varying(255),
    name character varying(255) NOT NULL,
    online boolean NOT NULL,
    password character varying(255),
    port integer NOT NULL,
    router_os_version character varying(255),
    uptime character varying(255),
    use_ssl boolean NOT NULL,
    username character varying(255)
);

ALTER TABLE public.routers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.routers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.staff_users (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    email character varying(255),
    full_name character varying(255) NOT NULL,
    last_login_at timestamp(6) with time zone,
    password_hash character varying(255) NOT NULL,
    phone_number character varying(255),
    role character varying(255) NOT NULL,
    seeded boolean NOT NULL,
    username character varying(255) NOT NULL,
    CONSTRAINT staff_users_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MANAGER'::character varying, 'ACCOUNTANT'::character varying, 'SUPPORT'::character varying])::text[])))
);

ALTER TABLE public.staff_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.staff_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscribers (
    id bigint NOT NULL,
    bandwidth character varying(255),
    created_at timestamp(6) with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    monthly_fee numeric(10,2) NOT NULL,
    paid_until timestamp(6) with time zone NOT NULL,
    phone_number character varying(255) NOT NULL,
    pppoe_password character varying(255) NOT NULL,
    pppoe_username character varying(255) NOT NULL,
    reminded_for_expiry timestamp(6) with time zone,
    status character varying(255) NOT NULL,
    auto_stk_for_expiry timestamp(6) with time zone,
    last_payment_at timestamp(6) with time zone,
    last_payment_method character varying(255),
    created_by character varying(255),
    branch_id bigint,
    last_seen_online_at timestamp(6) with time zone,
    router_id bigint,
    usage_reset_at timestamp(6) with time zone,
    data_used_mb bigint,
    CONSTRAINT subscribers_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'SUSPENDED'::character varying])::text[])))
);

ALTER TABLE public.subscribers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscribers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subscription_payments (
    id bigint NOT NULL,
    amount numeric(10,2) NOT NULL,
    checkout_request_id character varying(255),
    completed_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone NOT NULL,
    method character varying(255) NOT NULL,
    months integer NOT NULL,
    mpesa_receipt_number character varying(255),
    status character varying(255) NOT NULL,
    subscriber_id bigint NOT NULL,
    CONSTRAINT subscription_payments_method_check CHECK (((method)::text = ANY ((ARRAY['MPESA'::character varying, 'CASH'::character varying])::text[]))),
    CONSTRAINT subscription_payments_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SUCCESS'::character varying, 'FAILED'::character varying])::text[])))
);

ALTER TABLE public.subscription_payments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subscription_payments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.support_tickets (
    id bigint NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    customer_name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    priority character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    subject character varying(255) NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    resolved_at timestamp(6) with time zone,
    resolved_by character varying(255),
    work_started_at timestamp(6) with time zone,
    CONSTRAINT support_tickets_priority_check CHECK (((priority)::text = ANY ((ARRAY['LOW'::character varying, 'MEDIUM'::character varying, 'HIGH'::character varying])::text[]))),
    CONSTRAINT support_tickets_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'IN_PROGRESS'::character varying, 'RESOLVED'::character varying])::text[])))
);

ALTER TABLE public.support_tickets ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_tickets_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.task_notes (
    id bigint NOT NULL,
    author character varying(255) NOT NULL,
    body character varying(2000),
    created_at timestamp(6) with time zone NOT NULL,
    event_id bigint NOT NULL,
    from_admin boolean NOT NULL,
    photo_filename character varying(255)
);

ALTER TABLE public.task_notes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.task_notes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tax_settings (
    id bigint NOT NULL,
    address_line character varying(255),
    invoice_prefix character varying(255),
    kra_pin character varying(255),
    legal_name character varying(255),
    prices_include_vat boolean NOT NULL,
    updated_at timestamp(6) with time zone,
    vat_enabled boolean NOT NULL,
    vat_rate numeric(5,2) NOT NULL
);

CREATE TABLE public.technicians (
    id bigint NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    full_name character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    phone_number character varying(255),
    username character varying(255) NOT NULL,
    can_pppoe boolean,
    can_vouchers boolean
);

ALTER TABLE public.technicians ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technicians_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.ticket_assignees (
    ticket_id bigint NOT NULL,
    technician_id bigint
);

CREATE TABLE public.ticket_messages (
    id bigint NOT NULL,
    body character varying(4000) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    from_admin boolean NOT NULL,
    ticket_id bigint NOT NULL
);

ALTER TABLE public.ticket_messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ticket_messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.trial_claims (
    phone_number character varying(255) NOT NULL,
    claimed_at timestamp(6) with time zone NOT NULL,
    voucher_code character varying(255) NOT NULL
);

CREATE TABLE public.voucher_batches (
    id bigint NOT NULL,
    agent_id bigint,
    code_length integer,
    count integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    created_by character varying(255),
    custom_minutes integer,
    note character varying(300),
    prefix character varying(255),
    reference character varying(255) NOT NULL,
    plan_id bigint
);

ALTER TABLE public.voucher_batches ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.voucher_batches_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.vouchers (
    id bigint NOT NULL,
    activated_at timestamp(6) with time zone,
    code character varying(255) NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    expires_at timestamp(6) with time zone,
    phone_number character varying(255),
    status character varying(255) NOT NULL,
    plan_id bigint NOT NULL,
    custom_duration_minutes integer,
    bound_mac character varying(255),
    created_by character varying(255),
    batch_id bigint,
    CONSTRAINT vouchers_status_check CHECK (((status)::text = ANY ((ARRAY['UNUSED'::character varying, 'ACTIVE'::character varying, 'EXPIRED'::character varying])::text[])))
);

ALTER TABLE public.vouchers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.vouchers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT agents_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT branches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.c2b_payments
    ADD CONSTRAINT c2b_payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.custom_plan_settings
    ADD CONSTRAINT custom_plan_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.direct_messages
    ADD CONSTRAINT direct_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.expenses
    ADD CONSTRAINT expenses_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fiber_nodes
    ADD CONSTRAINT fiber_nodes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fiber_routes
    ADD CONSTRAINT fiber_routes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT invoices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.leads
    ADD CONSTRAINT leads_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ledger_adjustments
    ADD CONSTRAINT ledger_adjustments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.maintenance_events
    ADD CONSTRAINT maintenance_events_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.messaging_settings
    ADD CONSTRAINT messaging_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.mikrotik_settings
    ADD CONSTRAINT mikrotik_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_templates
    ADD CONSTRAINT notification_templates_pkey PRIMARY KEY (template_key);

ALTER TABLE ONLY public.outbound_messages
    ADD CONSTRAINT outbound_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payment_gateways
    ADD CONSTRAINT payment_gateways_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.payout_requests
    ADD CONSTRAINT payout_requests_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT plans_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.portal_settings
    ADD CONSTRAINT portal_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.promotions
    ADD CONSTRAINT promotions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.routers
    ADD CONSTRAINT routers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.staff_users
    ADD CONSTRAINT staff_users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscribers
    ADD CONSTRAINT subscribers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subscription_payments
    ADD CONSTRAINT subscription_payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.support_tickets
    ADD CONSTRAINT support_tickets_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.task_notes
    ADD CONSTRAINT task_notes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.tax_settings
    ADD CONSTRAINT tax_settings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.technicians
    ADD CONSTRAINT technicians_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.ticket_messages
    ADD CONSTRAINT ticket_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.trial_claims
    ADD CONSTRAINT trial_claims_pkey PRIMARY KEY (phone_number);

ALTER TABLE ONLY public.voucher_batches
    ADD CONSTRAINT uk15e3cyoovq04ixjaeqms0e26j UNIQUE (reference);

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT uk30ftp2biebbvpik8e49wlmady UNIQUE (code);

ALTER TABLE ONLY public.staff_users
    ADD CONSTRAINT uk84ntv1iab9fa9byg67plxw9fb UNIQUE (username);

ALTER TABLE ONLY public.ticket_assignees
    ADD CONSTRAINT uk9jo0vbsav3kcocn5u0jl7o64 UNIQUE (ticket_id, technician_id);

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT ukagm98wn5ln6uoh6o9hx25ogic UNIQUE (serial_number);

ALTER TABLE ONLY public.payment_gateways
    ADD CONSTRAINT ukcqtkkcb25aj7kea9ekhmwraw3 UNIQUE (kind);

ALTER TABLE ONLY public.subscribers
    ADD CONSTRAINT ukdcruxi3hijdrrqtts1bq9f9in UNIQUE (pppoe_username);

ALTER TABLE ONLY public.c2b_payments
    ADD CONSTRAINT ukdq80j5ka4sni3wdwqvepfh70w UNIQUE (transaction_id);

ALTER TABLE ONLY public.technicians
    ADD CONSTRAINT ukegwmhfw64790tchkqrw2ejkp4 UNIQUE (username);

ALTER TABLE ONLY public.branches
    ADD CONSTRAINT ukhw68nd07qk3jrjfg70qxq9vb7 UNIQUE (name);

ALTER TABLE ONLY public.plans
    ADD CONSTRAINT ukj2syv9y60858xbq169nbeg7ea UNIQUE (name);

ALTER TABLE ONLY public.plan_routers
    ADD CONSTRAINT ukloasj2enakl9d9gdopnnkyw4u UNIQUE (plan_id, router_id);

ALTER TABLE ONLY public.agents
    ADD CONSTRAINT ukmq85r3qbgmcf1bofga590ualo UNIQUE (code);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukno13v2ok5tbpx0u34ur4fev7f UNIQUE (voucher_id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT ukofo1541o09ownoe6yotjne7nc UNIQUE (checkout_request_id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT ukpa4f04a5qcpc80w6x1ry6v6o1 UNIQUE (number);

ALTER TABLE ONLY public.routers
    ADD CONSTRAINT ukr3ggy8jgfei5b45yxqfveptda UNIQUE (name);

ALTER TABLE ONLY public.subscription_payments
    ADD CONSTRAINT ukru6nlkiex50iqs5h0llp7kg60 UNIQUE (checkout_request_id);

ALTER TABLE ONLY public.voucher_batches
    ADD CONSTRAINT voucher_batches_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT vouchers_pkey PRIMARY KEY (id);

CREATE INDEX idx_outbound_created ON public.outbound_messages USING btree (created_at);

CREATE INDEX idx_outbound_status ON public.outbound_messages USING btree (status);

ALTER TABLE ONLY public.ticket_assignees
    ADD CONSTRAINT fk3eq2n7qyk6u57w80be0lmwc63 FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id);

ALTER TABLE ONLY public.vouchers
    ADD CONSTRAINT fk5vlj7ku5vleok7k15u0gvlmkg FOREIGN KEY (plan_id) REFERENCES public.plans(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fk70f50cqfiyp9w8qi5fgikvsxd FOREIGN KEY (plan_id) REFERENCES public.plans(id);

ALTER TABLE ONLY public.subscription_payments
    ADD CONSTRAINT fk8557mj4ax68byyq5egg5l6bv7 FOREIGN KEY (subscriber_id) REFERENCES public.subscribers(id);

ALTER TABLE ONLY public.voucher_batches
    ADD CONSTRAINT fk8knf4vk5rg885tpij69ayou1b FOREIGN KEY (plan_id) REFERENCES public.plans(id);

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkcdghxhl44dtjheg9o9emtwx2 FOREIGN KEY (voucher_id) REFERENCES public.vouchers(id);

ALTER TABLE ONLY public.plan_routers
    ADD CONSTRAINT fkef25vbv37addrn15tf0o5rm2t FOREIGN KEY (plan_id) REFERENCES public.plans(id);

ALTER TABLE ONLY public.ticket_messages
    ADD CONSTRAINT fkf95vo0g1fx8hddsno1j8jtd4o FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id);

ALTER TABLE ONLY public.invoices
    ADD CONSTRAINT fkfa3gu0nwmdf2wr26ebbjtcl3i FOREIGN KEY (subscriber_id) REFERENCES public.subscribers(id);

ALTER TABLE ONLY public.ledger_adjustments
    ADD CONSTRAINT fkipywgn3jf7swfs6cpmte5yb07 FOREIGN KEY (subscriber_id) REFERENCES public.subscribers(id);
