-- Bringing an ISP's book across from whatever they are on now.
--
-- The reason this exists is commercial, not technical: an ISP with three
-- thousand subscribers on Splynx will not retype them, and will not risk a
-- cutover that loses a month's invoicing. So the book is staged first, compared
-- against what the old system charged, and only promoted into real subscribers
-- when the operator is satisfied. Nothing here touches billing until promotion.

CREATE TABLE migration_batches (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source      VARCHAR(24)  NOT NULL,
    label       VARCHAR(200),
    -- STAGED once uploaded, PROMOTED once real subscribers exist, DISCARDED if
    -- the operator throws it away. A batch is never edited in place.
    status      VARCHAR(16)  NOT NULL DEFAULT 'STAGED',
    row_count   INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    created_by  VARCHAR(255),
    promoted_at TIMESTAMPTZ,
    promoted_by VARCHAR(255),
    notes       VARCHAR(2000)
);

CREATE TABLE migration_rows (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        BIGINT       NOT NULL REFERENCES migration_batches(id) ON DELETE CASCADE,
    -- Their id in the old system. Kept so a second upload of the same export
    -- recognises what it has already seen instead of duplicating the book.
    external_id     VARCHAR(120),
    full_name       VARCHAR(255),
    phone_number    VARCHAR(64),
    pppoe_username  VARCHAR(120),
    pppoe_password  VARCHAR(120),
    plan_name       VARCHAR(200),
    monthly_price   NUMERIC(12,2),
    static_ip       VARCHAR(64),
    external_status VARCHAR(64),
    -- What the old system says they owe or are in credit for. Informational:
    -- money is never moved by an import.
    balance         NUMERIC(12,2),
    paid_until      TIMESTAMPTZ,
    -- NEW, COLLISION (somebody here already has that username or phone) or
    -- INCOMPLETE (not enough to make a subscriber out of).
    verdict         VARCHAR(16)  NOT NULL,
    verdict_note    VARCHAR(500),
    -- The plan this row would be given here, resolved by name at staging time.
    matched_plan_id BIGINT,
    -- Set only once the row becomes a real customer.
    subscriber_id   BIGINT,
    raw             VARCHAR(4000)
);

CREATE INDEX idx_migration_rows_batch ON migration_rows (batch_id);
CREATE INDEX idx_migration_rows_verdict ON migration_rows (batch_id, verdict);

-- Where a promoted customer came from, so a support call about a strange
-- balance can be traced back to the old system rather than guessed at.
ALTER TABLE subscribers
    ADD COLUMN migrated_from    VARCHAR(24),
    ADD COLUMN migrated_ref     VARCHAR(120),
    ADD COLUMN migrated_at      TIMESTAMPTZ;
